x-common-orch-config: &orch-common
  image: small-orch:latest
  build:
    context: .
  volumes:
    - ./small_orch:/usr/src/app/small_orch
  env_file: ./docker/orch-backend.env
  depends_on:
    orch-db:
      condition: service_started
  networks:
    - orch-local

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - orch-local

  orch-db:
    container_name: orch-core-db
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - orch-db-data:/var/lib/postgresql/data
      - ./docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - orch-local

  orch-ui:
    container_name: orch-ui
    image: ghcr.io/workfloworchestrator/example-orchestrator-ui:latest
    env_file: ./docker/orch-ui.env
    ports:
      - 3000:3000
    networks:
      - orch-local
    depends_on:
      orch-backend:
        condition: service_started

  orch-backend:
    <<: *orch-common
    container_name: orch-backend
    ports:
      - 8080:8080
    environment:
      EXECUTOR: ${EXECUTOR:-celery}

  orch-celery-worker:
    <<: *orch-common
    container_name: orch-celery-worker
    command:
      - watchfiles
      - --filter
      - python
      - --
      - "celery -A small_orch.celery_worker worker -E -l INFO -Q new_tasks,resume_tasks,new_workflows,resume_workflows --concurrency=1"
    depends_on:
      - orch-backend

volumes:
  orch-db-data:
    name: small-orch-db-data

networks:
  orch-local:
    name: small-orch-local
