[project]
authors = [{ name = "Alexander Ray", email = "awray2@es.net" }]
license = { text = "Apache License 2.0" }
requires-python = "<3.13,>=3.11"
dependencies = ["orchestrator-core[celery]<3.0.0,>=2.7.3", "uvicorn>=0.32.1"]
name = "test-small-orch"
version = "0.1.0"
description = "Small example testing SURF WFO library"
readme = "README.md"

[tool.uv]
dev-dependencies = ["black>=25.1.0", "ruff>=0.9.7"]

[tool.black]
line-length = 100
